[package]
name = "jwt"
type = "lib"
authors = ["saleel"]
compiler_version = ">=0.35.0"

[dependencies]
noir_rsa = { tag = "v0.3.1", git = "https://github.com/noir-lang/noir_rsa", directory="lib" }
string_search = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_string_search" }
noir_base64 = { tag = "v0.2.3", git =  "https://github.com/noir-lang/noir_base64" }
zkemail = { tag = "v0.3.1", git = "https://github.com/zkemail/zkemail.nr", directory="lib" } # for partial SHA
