[package]
name = "jwt"
type = "lib"
version = "0.2.0"
authors = ["saleel"]
compiler_version = ">=0.36.0"

[dependencies]
rsa = { git = "https://github.com/noir-lang/noir_rsa", tag = "v0.4.0", directory="lib" }
base64 = { git =  "https://github.com/noir-lang/noir_base64", tag = "v0.3.0" }
string_search = { git = "https://github.com/olehmisar/noir_string_search", tag = "v0.3.0" } # switch to noir-org when 0.36.0 is merged
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.4.1" }
zkemail = { git = "https://github.com/zkemail/zkemail.nr", tag="update-deps", directory="lib" } # for partial SHA
